* ox-twbs

** Summary

Export [[http://orgmode.org/][org-mode]] docs as HTML compatible with [[http://getbootstrap.com/][Twitter Bootstrap]].

** Example

The following [[https://raw.githubusercontent.com/marsmining/ox-twbs/master/example/eg0.org][org source]] exports to [[http://clubctrl.com/org/prog/ox-twbs.html][this html]].

** Description

This library implements an HTML back-end for exporting org-mode docs
as HTML compatible with Twitter Bootstrap. The [[http://getbootstrap.com/javascript/#affix][Affix.js]] library is
used for a dynamic table of contents. The goal was to have a clean and
modern look to publishing my org files.

With no options, the publishing function =org-twbs-publish-to-html=
will export HTML with jQuery and Bootstrap resources included via
the [[http://osscdn.com][osscdn]] provided by [[https://www.maxcdn.com][MAXCDN]]. This default is [[https://github.com/marsmining/ox-twbs/blob/ec2c35fd5e2888b80f4703e2aaec50a7cb04ad1b/ox-twbs.el#L994-L1030][defined here]].

Derived from a part of [[http://www.gnu.org/software/emacs/][GNU Emacs]], =ox-html.el=, which was written by
Carsten Dominik and Jambunathan K. Apart from the style changes, a lot
of the legacy support for pre-html5 has been removed to make the code
simpler.

** Install

*** via package.el

Latest builds available on [[http://melpa.org/#/][MELPA]] and for a bit more stability, use
[[http://stable.melpa.org/#/][MELPA Stable]]. You can install ~ox-twbs~ using the following command:

=M-x package-install [RET] ox-twbs [RET]=

If the installation doesn't work try refreshing the package list:

=M-x package-refresh-contents [RET]=

*** Manual

Put ~ox-twbs.el~ in your load path and require it. Alternatively, open
=ox-twbs.el= in your buffer and run =package-install-file=, which will
compile and install the package in your package folder.

** Usage

Open or create an org file and run ~org-twbs-export-to-html~. This
will create an HTML file in the same dir as your org file.

You will more likely want more control and automation of the export
process. You can read [[http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][the org-mode docs]] on setting up your project. An
example configuration might look like:

#+BEGIN_SRC elisp
  (setq org-publish-project-alist
        '("org-notes"
          :base-directory "~/org/"
          :publishing-directory "~/public_html/"
          :publishing-function org-twbs-publish-to-html
          :with-sub-superscript nil
          ))
#+END_SRC

Using the above config, you can run: =org-publish-all=

And you might create a function which publishes the current buffers
file and opens it in your system's default browser. Here is what I
use in my emacs config:

#+BEGIN_SRC elisp
  (defun my-org-publish-buffer ()
    (interactive)
    (save-buffer)
    (save-excursion (org-publish-current-file))
    (let* ((proj (org-publish-get-project-from-filename buffer-file-name))
           (proj-plist (cdr proj))
           (rel (file-relative-name buffer-file-name
                                    (plist-get proj-plist :base-directory)))
           (dest (plist-get proj-plist :publishing-directory)))
      (browse-url (concat "file://"
                          (file-name-as-directory (expand-file-name dest))
                          (file-name-sans-extension rel)
                          ".html"))))
#+END_SRC

And bind the above command. I'm on OSX and happen to use ~CMD-\~.

#+BEGIN_SRC elisp
  (add-hook 'org-mode-hook
            (lambda ()
              (local-set-key (kbd "s-\\") 'my-org-publish-buffer)))
#+END_SRC

** General Org Tips

To specify a title of your org doc, other than the default:

: #+TITLE: My Doc

To quickly add blocks, check this [[http://orgmode.org/manual/Easy-Templates.html#Easy-Templates][easy template]] section of org manual.

Be sure to understand how to [[http://orgmode.org/manual/Editing-source-code.html#Editing-source-code][edit source code blocks]].

** Todo

Contributions are welcome! A list of potential fixes and enhancements
follows:

- Allow users to more easily add a Twitter Bootstrap theme
- Document areas where this package deviates from org-mode manual on
  [[http://orgmode.org/manual/HTML-export.html#HTML-export][HTML export]]
- Improve Affix.js plugin scroll-spying/following
- Ensure this package works well with org's sitemap function
